// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"sync/biz/handler"
)

func register(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	r.POST("/sync", handler.Sync)
	r.GET("/sync/:vid", handler.SyncStatus)
	r.GET("/play/:vid", handler.Play)
}
